# Generated by Django 6.0.4 on 2026-05-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcycle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
