# Generated by Django 6.0.5 on 2026-05-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetcycle_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=20)),
                ('FakeBackUP', models.CharField(max_length=40)),
            ],
        ),
    ]
